---
title: "Size-based Population Model to Southern Gulf of Saint Lawrence Snow Crab"
author: "Tobie Surette"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Population models

Population models are mathematical constructs which attempt to quantitatively describe how abundance indices are observed to vary over time. 

When successful, models capture some essence of the variation observed in the data, providing some insight on underlying biological processes, the impact of fishing activities, which can be used to predict future dynamics of the population.

The complexity of these models can range from the very simple to the complex and very detailed.

In this report, we present a size-based population model of the annual dynamics of the Southern Gulf of Saint Lawrence snow crab population.

Though size-based, crab are partitioned by instar, i.e. the number of benthic moults crab have undergone, allowing for the specification of biological effects based on instar, as well as on size or year.

Instars are identified using a structured growth process which models the expected growth-at-moult between instars and its variation, which is used to fit a set of modes, the product of instar growth constraints, observed in the annual size-frequency data.

Biological processes included in the model are growth-at-moult, population recruitment, natural and fishing-related mortality, skip-moulting probabilities and moult-to-maturity probabilities.

Sampling-related processes are incorporated in the form of survey trawl size-selectivity curves as well as global year effects, intended to shed light on potential differences in catchability between survey years, which have been associated with vessel changes, as well as other survey sampling changes.

For the purposes of this study, the snow crab population is assumed to be closed, which is a reasonnble assumption as the stock is largely bounded by the Gaspé Pensinsula to the North, Cape Breton Island to the Southeast, and the deep warm waters of the Laurentian Channel between the two, though limited movement of crab along the margins of Gaspé and Cape Breton are known to occur.

Limits of population models:
Population models such as those presented here are often over-parameterized, meaning that in some way the amount of information being estimated exceeds the inherent information content of the data. As such, such analyses often yield multiple solutions, representing potentially very different biological states, which explain the data to a similar degree. 

Often, external biological information or assumptions are imposed on the model to constrain the parameter space to solutions which are more consistent with biological knowledge.

Population model development as such is generally a protracted process of many iterations of adding or removing features, testing the model against a suite of diagnostics, such as residual analyses, predictive tests, cross-validations. 

From these, the behaviour of the model under various assumptions becomes known, and experience and a feelings regarding its robustness is gained.

In this context, the model described here is not presented as a fait accompli, but rather as a presentation of the strategy and as a prototype which has the right balance of simplicity and complexity to provide, in the short-term, improvements in: 

- the retroactive estimation and prediction of annual variations in skip-moulting and moult-to-maturity probabilities. 
- the prediction of future population dynamics, specifically fishery recruitment.
- relative catchability estimates between different survey years, or survey vessels, which may provide a means of retroactively standardizing the snow crab survey abundance and biomass time series.

As side-benefits, the proposed modeling framework may also be expected to yield:

- estimates of annual growth estimates, in the form of mean instar size estimates.
- fishery-independent estimates of fishing mortality, including discard mortality.
- a framework for modeling spatially-reference stock dynamics.


In this way, the population model represent a synthesis of various biological and sampling processes.

Thus, population models can potentially provide information regarding a slew of biological and survey effects and their interaction, 
although this interaction often means that various solutions may come about which explain the data 
to a similar degree ... i.e. there may be competing solutions, different suppositions, which may explain the observed patterns in the data to a similar degree.
So the model requires good run of diagnostics and tests of robustness in order to explore the limits and stability of any identified solutions.

## To do: 
- Kriged estimates for fixed versus moved grids stations for commercial crab.
- Depth-based estimation.
- Implement fishing mortality effect : a scaled-logistic-type effect which kicks in around 95mm.
- a_year / (1 + exp(4*m*(x - 95))), scale varies by year.
- skip-moulting variation by year : global year increase (i.e. not instar specific).

- Remove superfluous p_mat and p_skip row/column
- Add interaction error / mortality variability
- Add vessel effect
- Add mature growth modification   
- Display histograms with immatures y and mature y + 1 
- Add annual global scaling effect.
- Improve instar variance fit for matures.
- Improve growth mean fit for immature instars VIII and IX.
- Implement log_mu_year which better controls variability within instars
- Model seems to be growing adolescents too fast, but log_mu_year shrinks them back down ... an effort to....?

## Data 

Source data for the model came from the annual snow crab survey from 2006 to 2020.

Average length-frequencies were standardized by trawl swept area were calculated by survey year, sex and morphometric maturity.

For the purposes of evaluating and developing the snow crab model, the time series was limited to the period from  2006 to 2020, owing to the spatial homogeneity of the sampling design during this period. The survey was marginally expanded in 2011 and this will need to be considered when interpreting the model results.

The time series will be extended in future version of the model into past surveys where changing survey area and heterogeneous spatial distributions may lead to some degree of scaling issues, which will hopefully be corrected by the model.

This treatment of densities as frequencies allows for approximate statistical 



## Model specification

### Description:

In the literature, benthic stages of snow crab instars are numbered using roman numerals, with I representing the first stage after the megalopses larvae have settled on the bottom and moulted.

For both sexes, instars I to VIII are considered sexually immature and characterized by high relative growth rates. Adolescence begins with the onset of gonadal development at instar VIII, which is characterized by lower relative growth rates. 

Sexual maturity, equated here as the terminal moult accompanied by characteristic morphometric changes, is attained at instars IX or larger. The vast majority of female snow crabs reach sexual maturity at instars IX and X. 

Females growing to instar XI and larger were considered as being too rare an occurrence to be considered in the analysis. Mature male snow crab moult to maturity over a much wider size range, from instars IX to XIII. Instar XIV males were considered as relatively rare and not considered in the model. It follows that instar X in females and instar XII in males were the largest adolescent instars.
Growth in the model is a combination of two separate processes: one which specifies the probability of moulting from one instar to the next, and the other which specifies the predicted increase in size and its variation when moulting. 

Two moulting processes were considered. Sexual maturation was modelled as the proportions of crab that undergo the terminal moult to maturity by instar and year. Although the probability of moulting to maturity for the largest adolescent instars, i.e. instar IX in females and XII in males, was considered to be 1, instars VIII in females and instars VIII-XI in males show variable proportions from year-to-year. Skip-moulting was only considered for adolescent males, was similarly modelled by instar and year. Moulting was considered to occur annually all instars.

Although the odd instar I, II and III do appear in survey catches, only instar IV crab are present in sufficient amounts to be analyzed by the model. For practical reasons, annual recruitment to the population was defined as the abundance of instar IV. 

### Formal definition:

Instar carapace width sizes were assumed to follow a Gaussian distribution curve with structured mean and error. Means for successive instars  instar were defined iteratively as follows, allowing for known differences in growth between immature and adolescent crab:
$$
   \mu_{k+1} = \alpha_{imm}\mu_{k} + \beta_{imm}, \text{ for }  k \le 8  \\
   \mu_{k+1} = \alpha_{ado}\mu_{k} + \beta_{ado}, \text{ for }  k > 8  \\
$$
where $\mu_{k}$ is the mean for the $k^{th}$ instar, $\alpha_{imm}$ and $\beta_{ado}$ are Hiatt slope and intercept parameters, respectively for immature crab, with $\alpha_{ado}$ and $\beta_{ado}$ being the corresponding adolescent phase parameters.

Instar standard errors are similarly defined, but allow for additional error inflation in the form of two positive parameters $\gamma_{imm}$ and $\gamma_{ado}$:

$$
   \sigma_{k+1} = (\alpha_{imm} + \gamma_{imm}) \sigma_{k}, \text{ for } k \le 8  \text{ and }  \gamma_{imm} > 0 \\
   \sigma_{k+1} = (\alpha_{ado} + \gamma_{ado}) \sigma_{k}, \text{ for } k > 8  \text{ and }  \gamma_{ado} > 0 \\   
$$
Growth for mature crab was modified slightly by including an additive term $\Delta_{mat}$:

$$
   \mu_{k}^{mat} = \mu_{k}^{ado} + \Delta_{mat}
$$
Based on biological considerations, we expect that $\Delta_{mat} < 0$.

Inferences on growth-at-moult can often be obtained from analysis of these modes and the approach has traditionally been to treat the data as arising from finite mixture model with probability density of the form:

$$
   \sum_{k=1}^{K} \pi_k \phi \left(x | \mu_k , \sigma_k^2  \right)
$$
where $k$ indexes the instars, $x$ represents crab size, $\pi_k$ are the proportions of each instar in the sample, $\mu_k$ are their mean sizes and $\sigma_k^2$ are their variances.

However, inference for larger instars is generally more uncertain owing to increasing variability in growth during adolescence, which resulting in size overlap between successive instars at these stages.

### Model Assumptions

- There is a largest immature instar, for which all individuals either skip-moult or moult to maturity the following year.
- Skip-moulters moult to maturity the following year.
- Skip-moulters only exist from instar IX and onward.
- Females have negligible amounts of skip-moulting.
- Matures exist only from instar IX onward.
- 

### Population dynamics equations

Stage-based processes affecting the population dynamics are the probability of moulting to maturity from one instar to the next, the probability of an instar skipping a moult (i.e. not growing and remaining mature) and annual mortality for immatures and matures.

The selectivity function is length-based, being a sigmoid-type function.

With $y$ indxing the survey year and $k$ indexing the instar, the population dynamics equations are as follows:

$$
\begin{aligned}
   n_{k,y}^{imm}  &= (1-p_{k-1,y-1}^{mat}) \times (1-p_{k-1}^{skip}) \times (1-M^{imm}) \times n_{k-1,y-1}^{imm} \\
   n_{k,y}^{skip} &= (1-p_{k-1,y-1}^{mat}) \times p_{k-1}^{skp} \times (1-M^{imm}) \times n_{k,y-1}^{imm} \\
   n_{k,y}^{rec}  &= (1-M^{mat}) \times \left[(1-p_{k-1}^{skp}) \times p_{k-1,y-1}^{mat} \times n_{k-1,y-1}^{imm} + n_{k-1,y-1}^{skip} \right] \\  
   n_{k,y}^{res}  &= (1-M^{mat}) \times \left[n_{k,y-1}^{rec} + n_{k,y-1}^{res} \right] \\ 
   n_{k,y}^{mat}  &= n_{k,y}^{rec} + n_{k,y}^{res}
\end{aligned}
$$
with the superscripts $imm$ representing regular immatures, $skip$ representing immatures which have skipped the previous moult, $rec$ representing new mature recruits, $res$ representing residuals matures and $mat$ representing all matures, i.e. the sum of recruits and residuals. 


|     Variable      | Description                                                         |
|:-----------------:|:--------------------------------------------------------------------|
| $n_{k,y}^{imm}$   | Population number of immature crab.
| $n_{k,y}^{skip}$  | Population number of immature crab which skipped the previous moult.
| $n_{k,y}^{rec}$   | Population number of new mature recruits.
| $n_{k,y}^{res}$   | Population number of old mature residuals (i.e. non-recruits).
| $n_{k,y}^{mat}$   | Population number of total mature crab.
| $M^{imm}$         | Annual proportion of immature crab which die off.
| $M^{mat}$         | Annual proportion of mature crab which die off.
| $p_{k,y}^{skip}$  | Annual proportion of immature crab which skip a moult. 
| $p_{k,y}^{mat}$   | Annual proportion of immature crab which moult to maturity. 


